
/*        Copyright (C) 2002 Oki Electric Industry Co.,Ltd.        */

/*******************************************************************
********************************************************************
****															****
****															****
****			Error Information Common header file			****
****			//公共错误信息									****
****						Ver 00.10							****
****															****
********************************************************************
/*	file name	DrvErrCmm.h									*/

#ifndef __DRVERRCMN_H__
#define __DRVERRCMN_H__
/*******************************************************
*
*	Data define
*   定义数据
********************************************************/
/*======================================================
	Return value
	//返回值
=======================================================*/
//#define	NO_ERROR							0x00000000
#define		ERROR_DRV_RESULT_CANCELED			0x20000000
#define		ERROR_DRV_RESULT_PARAMETER_ERROR	0x21000000
#define		ERROR_DRV_RESULT_SLIGHT_ALARM		0x22000000
#define		ERROR_DRV_RESULT_ALARM				0x23000000
#define		ERROR_DRV_RESULT_SYSTEM_ERROR		0x24000000
#define		ERROR_DRV_RESULT_INTERNAL_ERROR		0x25000000

/*======================================================
	Error type
	//错误类型
=======================================================*/

#define		ERROR_DRV_ROUTER					0x00001000
#define		ERROR_DRV_DEVICE					0x00002000
#define		ERROR_DRV_PROTOCOL					0x00003000
#define		ERROR_DRV_STARTUP					0x00004000

/*------------------------------------------------------
	ERROR_DRV_RESULT_CANCELED
-------------------------------------------------------*/
// Router driver
#define		ERROR_R_CANCELED_CLOSE		(ERROR_DRV_RESULT_CANCELED + ERROR_DRV_ROUTER + 0x0001)
#define		ERROR_R_CANCELED_RESET		(ERROR_DRV_RESULT_CANCELED + ERROR_DRV_ROUTER + 0x0002)

// Device driver
#define		ERROR_D_CANCELED_CLOSE		(ERROR_DRV_RESULT_CANCELED + ERROR_DRV_DEVICE + 0x0001)
#define		ERROR_D_CANCELED_RESET		(ERROR_DRV_RESULT_CANCELED + ERROR_DRV_DEVICE + 0x0002)

// Protocol driver
#define		ERROR_P_CANCELED_CLOSE		(ERROR_DRV_RESULT_CANCELED + ERROR_DRV_PROTOCOL + 0x0001)
#define		ERROR_P_CANCELED_RESET		(ERROR_DRV_RESULT_CANCELED + ERROR_DRV_PROTOCOL + 0x0002)

// StartUp driver
#define		ERROR_S_CANCELED_CLOSE		(ERROR_DRV_RESULT_CANCELED + ERROR_DRV_STARTUP + 0x0001)
#define		ERROR_S_CANCELED_RESET		(ERROR_DRV_RESULT_CANCELED + ERROR_DRV_STARTUP + 0x0002)

/*------------------------------------------------------
	ERROR_DRV_RESULT_PARAMETER_ERROR
-------------------------------------------------------*/
// Router driver
#define		ERROR_R_INVALID_DEVICE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_ROUTER + 0x0001)
#define		ERROR_R_INVALID_HANDLE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_ROUTER + 0x0002)
#define		ERROR_R_INVALID_LENGTH		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_ROUTER + 0x0003)
#define		ERROR_R_INVALID_PARAMETER	(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_ROUTER + 0x0004)
#define		ERROR_R_INVALID_POINTER		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_ROUTER + 0x0005)
#define		ERROR_R_INVALID_FILE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_ROUTER + 0x0006)
#define		ERROR_R_ACCESS_DENIDE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_ROUTER + 0x0007)

// Device driver
#define		ERROR_D_INVALID_DEVICE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_DEVICE + 0x0001)
#define		ERROR_D_INVALID_HANDLE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_DEVICE + 0x0002)
#define		ERROR_D_INVALID_LENGTH		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_DEVICE + 0x0003)
#define		ERROR_D_INVALID_PARAMETER	(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_DEVICE + 0x0004)
#define		ERROR_D_INVALID_POINTER		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_DEVICE + 0x0005)
#define		ERROR_D_INVALID_FILE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_DEVICE + 0x0006)
#define		ERROR_D_ACCESS_DENIDE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_DEVICE + 0x0007)

// Protocol driver
#define		ERROR_P_INVALID_DEVICE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_PROTOCOL + 0x0001)
#define		ERROR_P_INVALID_HANDLE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_PROTOCOL + 0x0002)
#define		ERROR_P_INVALID_LENGTH		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_PROTOCOL + 0x0003)
#define		ERROR_P_INVALID_PARAMETER	(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_PROTOCOL + 0x0004)
#define		ERROR_P_INVALID_POINTER		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_PROTOCOL + 0x0005)
#define		ERROR_P_INVALID_FILE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_PROTOCOL + 0x0006)
#define		ERROR_P_ACCESS_DENIDE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_PROTOCOL + 0x0007)

// StartUp driver
#define		ERROR_S_INVALID_DEVICE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_STARTUP + 0x0001)
#define		ERROR_S_INVALID_HANDLE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_STARTUP + 0x0002)
#define		ERROR_S_INVALID_LENGTH		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_STARTUP + 0x0003)
#define		ERROR_S_INVALID_PARAMETER	(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_STARTUP + 0x0004)
#define		ERROR_S_INVALID_POINTER		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_STARTUP + 0x0005)
#define		ERROR_S_INVALID_FILE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_STARTUP + 0x0006)
#define		ERROR_S_ACCESS_DENIDE		(ERROR_DRV_RESULT_PARAMETER_ERROR + ERROR_DRV_STARTUP + 0x0007)

/*------------------------------------------------------
	ERROR_DRV_RESULT_SLIGHT_ALARM
-------------------------------------------------------*/
// Router driver
#define		ERROR_R_WAIT_TIMEOUT		(ERROR_DRV_RESULT_SLIGHT_ALARM + ERROR_DRV_ROUTER + 0x0001)
#define		ERROR_R_BUFFER_OVERFLOW		(ERROR_DRV_RESULT_SLIGHT_ALARM + ERROR_DRV_ROUTER + 0x0002)

// Device driver
#define		ERROR_D_WAIT_TIMEOUT		(ERROR_DRV_RESULT_SLIGHT_ALARM + ERROR_DRV_DEVICE + 0x0001)
#define		ERROR_D_BUFFER_OVERFLOW		(ERROR_DRV_RESULT_SLIGHT_ALARM + ERROR_DRV_DEVICE + 0x0002)

// Protocol driver
#define		ERROR_P_WAIT_TIMEOUT		(ERROR_DRV_RESULT_SLIGHT_ALARM + ERROR_DRV_PROTOCOL + 0x0001)
#define		ERROR_P_BUFFER_OVERFLOW		(ERROR_DRV_RESULT_SLIGHT_ALARM + ERROR_DRV_PROTOCOL + 0x0002)

// StartUp driver
#define		ERROR_S_WAIT_TIMEOUT		(ERROR_DRV_RESULT_SLIGHT_ALARM + ERROR_DRV_STARTUP + 0x0001)
#define		ERROR_S_BUFFER_OVERFLOW		(ERROR_DRV_RESULT_SLIGHT_ALARM + ERROR_DRV_STARTUP + 0x0002)

/*------------------------------------------------------
	ERROR_DRV_RESULT_ALARM
-------------------------------------------------------*/
// Router driver
#define		ERROR_R_COMMUNICATION		(ERROR_DRV_RESULT_ALARM + ERROR_DRV_ROUTER + 0x0001)
#define		ERROR_R_DEVICE_NOT_FOUND	(ERROR_DRV_RESULT_ALARM + ERROR_DRV_ROUTER + 0x0002)

// Device driver
#define		ERROR_D_COMMUNICATION		(ERROR_DRV_RESULT_ALARM + ERROR_DRV_DEVICE + 0x0001)
#define		ERROR_D_DEVICE_NOT_FOUND	(ERROR_DRV_RESULT_ALARM + ERROR_DRV_DEVICE + 0x0002)

// Protocol driver
#define		ERROR_P_COMMUNICATION		(ERROR_DRV_RESULT_ALARM + ERROR_DRV_PROTOCOL + 0x0001)
#define		ERROR_P_DEVICE_NOT_FOUND	(ERROR_DRV_RESULT_ALARM + ERROR_DRV_PROTOCOL + 0x0002)

// StartUp driver
#define		ERROR_S_COMMUNICATION		(ERROR_DRV_RESULT_ALARM + ERROR_DRV_STARTUP + 0x0001)
#define		ERROR_S_DEVICE_NOT_FOUND	(ERROR_DRV_RESULT_ALARM + ERROR_DRV_STARTUP + 0x0002)

/*------------------------------------------------------
	ERROR_DRV_RESULT_SYSTEM_ERROR
-------------------------------------------------------*/
// Router driver
#define		ERROR_R_NOT_ENOUGH_MEMORY	(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_ROUTER + 0x0001)
#define		ERROR_R_INVALID_REGISTRY	(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_ROUTER + 0x0002)
#define		ERROR_R_CREATE_FILE			(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_ROUTER + 0x0003)
#define		ERROR_R_CREATE_THREAD		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_ROUTER + 0x0004)
#define		ERROR_R_CREATE_WINDOW		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_ROUTER + 0x0005)
#define		ERROR_R_CREATE_EVENT		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_ROUTER + 0x0006)
#define		ERROR_R_SET_EVENT			(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_ROUTER + 0x0007)
#define		ERROR_R_RESET_EVENT			(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_ROUTER + 0x0008)
#define		ERROR_R_CLOSE_HANDLE		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_ROUTER + 0x0009)

// Device driver
#define		ERROR_D_NOT_ENOUGH_MEMORY	(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_DEVICE + 0x0001)
#define		ERROR_D_INVALID_REGISTRY	(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_DEVICE + 0x0002)
#define		ERROR_D_CREATE_FILE			(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_DEVICE + 0x0003)
#define		ERROR_D_CREATE_THREAD		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_DEVICE + 0x0004)
#define		ERROR_D_CREATE_WINDOW		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_DEVICE + 0x0005)
#define		ERROR_D_CREATE_EVENT		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_DEVICE + 0x0006)
#define		ERROR_D_SET_EVENT			(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_DEVICE + 0x0007)
#define		ERROR_D_RESET_EVENT			(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_DEVICE + 0x0008)
#define		ERROR_D_CLOSE_HANDLE		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_DEVICE + 0x0009)

// Protocol driver
#define		ERROR_P_NOT_ENOUGH_MEMORY	(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_PROTOCOL + 0x0001)
#define		ERROR_P_INVALID_REGISTRY	(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_PROTOCOL + 0x0002)
#define		ERROR_P_CREATE_FILE			(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_PROTOCOL + 0x0003)
#define		ERROR_P_CREATE_THREAD		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_PROTOCOL + 0x0004)
#define		ERROR_P_CREATE_WINDOW		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_PROTOCOL + 0x0005)
#define		ERROR_P_CREATE_EVENT		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_PROTOCOL + 0x0006)
#define		ERROR_P_SET_EVENT			(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_PROTOCOL + 0x0007)
#define		ERROR_P_RESET_EVENT			(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_PROTOCOL + 0x0008)
#define		ERROR_P_CLOSE_HANDLE		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_PROTOCOL + 0x0009)

// StartUp driver
#define		ERROR_S_NOT_ENOUGH_MEMORY	(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_STARTUP + 0x0001)
#define		ERROR_S_INVALID_REGISTRY	(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_STARTUP + 0x0002)
#define		ERROR_S_CREATE_FILE			(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_STARTUP + 0x0003)
#define		ERROR_S_CREATE_THREAD		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_STARTUP + 0x0004)
#define		ERROR_S_CREATE_WINDOW		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_STARTUP + 0x0005)
#define		ERROR_S_CREATE_EVENT		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_STARTUP + 0x0006)
#define		ERROR_S_SET_EVENT			(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_STARTUP + 0x0007)
#define		ERROR_S_RESET_EVENT			(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_STARTUP + 0x0008)
#define		ERROR_S_CLOSE_HANDLE		(ERROR_DRV_RESULT_SYSTEM_ERROR + ERROR_DRV_STARTUP + 0x0009)

/*------------------------------------------------------
	ERROR_DRV_RESULT_INTERNAL_ERROR
-------------------------------------------------------*/



/*******************************************************
*	Structure define
*	结构定义
********************************************************/
#pragma pack(1)
/*======================================================
	Error information structure
	错误通知结构
=======================================================*/
typedef struct _COMMON_ERRORINFO 
{
	DWORD	dwType;	//错误类型					// Error type
	DWORD	dwDetail;//错误细节					// Error detail
	DWORD	dwPosition;	//错误位置				// Error position(High WORD:Module No. Low WORD:line乯
} CMNERRINFO, *LPCMNERRINFO;

typedef struct _DRIVER_ERRORINFO 
{
	DWORD		dwNumOfBlock;//错误通知			// Error information block number
	DWORD		dwNumOfSetBlock;//错误设置块说明		// Error set block specification
	CMNERRINFO	ErrInfoBlock[5];//错误通知块排列			// Error information block array
} DRVERRINFO, *LPDRVERRINFO;

#endif
/*        Copyright (C) 2002 Oki Electric Industry Co.,Ltd.        */
